version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "pl-startingXI"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1klhrm1b8p8bt"
s3_prefix = "pl-startingXI"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
